Traceback (most recent call last):
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Make a simple regression plot

# Create the figure
fig, ax = plt.subplots(1,1, figsize=(5,4))

# Plot the line
sns.regplot(x=df.AGE, y=df.TRUST, scatter_kws={"color": "#C06C84"}, line_kws={"color":"#7D0552"}, ax=ax)

# Include this command such that all the elements of the plot appear in the figure
plt.tight_layout()

# Save figure
plt.savefig('figure.tif', dpi=300, format="tiff")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[12], line 4[0m
[0;32m      1[0m [38;5;66;03m# Make a simple regression plot[39;00m
[0;32m      2[0m 
[0;32m      3[0m [38;5;66;03m# Create the figure[39;00m
[1;32m----> 4[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m,[38;5;241m1[39m, figsize[38;5;241m=[39m([38;5;241m5[39m,[38;5;241m4[39m))
[0;32m      6[0m [38;5;66;03m# Plot the line[39;00m
[0;32m      7[0m sns[38;5;241m.[39mregplot(x[38;5;241m=[39mdf[38;5;241m.[39mAGE, y[38;5;241m=[39mdf[38;5;241m.[39mTRUST, scatter_kws[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mcolor[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m#C06C84[39m[38;5;124m"[39m}, line_kws[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mcolor[39m[38;5;124m"[39m:[38;5;124m"[39m[38;5;124m#7D0552[39m[38;5;124m"[39m}, ax[38;5;241m=[39max)

[1;31mNameError[0m: name 'plt' is not defined

